# Generated by Django 4.2.11 on 2024-03-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='courses',
            new_name='course',
        ),
    ]
