# Generated by Django 4.2.11 on 2024-03-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_rename_courses_course_rename_courses_details_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='materials_provide',
            field=models.CharField(max_length=300),
        ),
    ]
